name: Build Firmware
on:
  workflow_dispatch:
  schedule:
    - cron: '17 2 1 * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Firmware
        run: |
          ./build.sh

      - name: Cache Image Builder
        uses: actions/cache@v4
        id: cache-tooling-binaries
        with:
          path: |
            scratch/*.tar.xz
            scratch/openwrt-imagebuilder-*/dl
          key: ${{ hashFiles('build.sh', 'packages.txt', 'disabled-services.txt') }}

      - name: Release build artifacts
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          prerelease: false
          name: Banana BPI R3 Firmware v23.05.3
          tag: v23.05.3-${{ env.REVISION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: scratch/openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64/bin/targets/mediatek/filogic/*
